### PR TITLE
Version 6.0 (PSR-2 and big refactoring)

### PR DESCRIPTION
**Pull request by MAXakaWIZARD**
This is work in progress. Any feedback is appreciated.

### CODE REVIEW

**Comment by gonzofy** [comment]
@MAXakaWIZARD thanks for taking a stab at this. Feedback is that it looks good.

One thing that's a little frustrating in GitHub is that the moving files around shows them as file deletions + additions (worth checking: did you use `git mv` vs. `mv` to move them around?) so it's hard to tell if anything changed within them. Can I assume that all the source files are basically unmodified except for renaming?

**Comment by MAXakaWIZARD** [comment]
@gonzofy Code logic was not touched. There were some file movings and code style fixes (to follow PSR-2). Also unit tests pass and I have also added more tests.

**Comment by MAXakaWIZARD** [comment]
@gonzofy We can also discuss what else should be added to this PR.

**Comment by gonzofy** [comment]
@MAXakaWIZARD Frankly it's already a big improvement in organization, and I'm tempted to merge it down and tag a 6.0.0 right now. However, I haven't spent time on the PSR-2 specifics; what more is needed to polish it off before a merge?

**Comment by MAXakaWIZARD** [comment]
@gonzofy All the code in this PR is PSR2-compliant. There is one more thing we should consider: bumping PHP version requirement if we can get any profit out of this.

**Comment by gonzofy** [comment]
@MAXakaWIZARD What benefit in bumping the version? Guaranteed availability of new features? Personally I'm on 5.6 so wouldn't mind bumping, but I'm also aware that many systems are still on older versions so don't want to unnecessarily exclude them from using the library.

**Comment by MAXakaWIZARD** [comment]
@gonzofy Old systems can use version `5.0`, for example. PHP `5.3` and `5.4` have reached their end of life, `5.5` will reach it in few months. So my suggestion is to bump PHP version at least to `5.4`.

**Comment by MAXakaWIZARD** [comment]
@gonzofy If you agree for `5.4`, I will make needed changes.

**Comment by MAXakaWIZARD** [comment]
@gonzofy I've added changelog and also removed PHP 7.0 from allowed failures in Travis config.

**Comment by MAXakaWIZARD** [comment]
@gonzofy Also I'd suggest to bump PHPUnit version for at least `~4.0`

**Comment by MAXakaWIZARD** [comment]
So proposed things are:
* change PHP version requirement to `^5.4 | ^7.0`
* change PHPUnit version requirement to `~4.0`

**Comment by gonzofy** [comment]
@MAXakaWIZARD I'm good with those proposals.

**Comment by MAXakaWIZARD** [comment]
@gonzofy I think we are good to go now.

**Pull request merged**
